spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_manager?serverTimezone=UTC
    username: root
    password: jucadrive01.
  sql:
    init:
      mode: always